name: dart_ipmi
description: A Dart library for controlling IPMI devices via a network.
version: 2.1.0
homepage: https://github.com/point-source/dart_ipmi

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  requests: ^4.4.1

dev_dependencies:
  dart_code_metrics: ^4.16.0
  lints: ^2.0.0
  test: ^1.16.0
